### ISSUE TITLE
Replace explicit passwords with secrets

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamindb-docker#9]
Currently, we have the passwords for login explicitly in the Dockerfile which is really bad. `laminci` would require a nox session which we don't have either.

How to solve

- [ ] Create 2 Github Actions secrets: user1password
- [ ] Update our login code to: `RUN lamin login testuser1@lamin.ai --password $user1password`
- [ ] Adapt the Dockerfile push workflow section to
```
- name: Build and push Docker image
  uses: docker/build-push-action@v4
  with:
    context: .
    file: ${{ matrix.dockerfile }}
    push: true
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
    build-args: LAMIN_PASSWORD=${{ secrets.user1password }}
  env:
    DOCKER_BUILDKIT: 1
```
